version: '3.8'

services:
  # PostgreSQL Database (Development)
  postgres:
    image: postgres:15-alpine
    container_name: ecommerce_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_dev_network

  # Redis Cache (Development)
  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis_dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - ecommerce_dev_network

  # pgAdmin (Development)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ecommerce_pgadmin_dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@ecommerce.com
      PGADMIN_DEFAULT_PASSWORD: dev_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"
    volumes:
      - pgadmin_dev_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ecommerce_dev_network

  # Redis Commander (Development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ecommerce_redis_commander_dev
    restart: unless-stopped
    environment:
      REDIS_HOSTS: redis:redis:6379
    ports:
      - "8083:8081"
    depends_on:
      - redis
    networks:
      - ecommerce_dev_network

  # Mailhog (Email testing in development)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ecommerce_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web interface
    networks:
      - ecommerce_dev_network

  # Next.js Application (Development)
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ecommerce_app_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres_dev_password@postgres:5432/ecommerce_db_dev?schema=public
      - REDIS_URL=redis://redis:6379
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key_here
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key_here
      - PAYTR_MERCHANT_ID=your_paytr_merchant_id_here
      - PAYTR_MERCHANT_KEY=your_paytr_merchant_key_here
      - PAYTR_MERCHANT_SALT=your_paytr_merchant_salt_here
      - NEXT_PUBLIC_PAYTR_ENABLED=true
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key-here
      - OPENSSL_CONF=/dev/null
    volumes:
      - .:/app
      - /app/node_modules
      - nextjs_cache:/app/.next
    depends_on:
      - postgres
      - redis
    networks:
      - ecommerce_dev_network

volumes:
  postgres_dev_data:
  redis_dev_data:
  pgadmin_dev_data:
  nextjs_cache:

networks:
  ecommerce_dev_network:
    driver: bridge